// =============================================================
// MACARIO — content/questions.js (Block 68)
//
// The trivia card and the pre-test and post-test questions, with their
// answers, inside the game itself. At the instructor's direction the
// answer key is no longer kept secret in the database: the game grades
// a test itself (assessment.js) and writes the score.
//
// This file is the built-in bank. The teacher may edit the questions
// and answers from the dashboard (teacher.html, Mga Tanong), which
// saves them to the assessment_items and act_trivia tables; when the
// database has questions for a test, those are used, and this file is
// the fallback when it has none or cannot be reached.
//
// Act I's items started as db/seeds/macario_items_v3.sql: ten matched
// pairs, pre-test item n the partner of post-test item n. correct is
// the 0-based index of the right choice. The questions are the
// teacher's to write and change, on the dashboard; this file is only
// the fallback (CLAUDE.md, Standing decisions). Acts II to IV were
// added on 9 Oct 2026 at the proponent's word, so every act has a test
// before the teacher writes one.
//
// passing is the share of a post-test a student must get right to
// pass. Below it, the student is offered a replay of the act and
// another try at the post-test (acts.js, finishAct).
// =============================================================

window.QUESTIONS = {
  1: {
    passing: 0.75,
    trivia: "Si Macario Sakay ay isa sa mga pinunong nagpatuloy ng laban para sa kalayaan kahit matapos ang panahon ng Espanya. Ngunit ang kanyang kuwento ay nagsimula sa isang ordinaryong araw sa Maynila, bilang isang karaniwang manggagawa.",
    pre: [
      { question: "Saan sa Maynila nagmula si Macario Sakay?",
        choices: ["Tondo", "Binondo", "Intramuros", "Malate"],
        correct: 0 },
      { question: "Bago sumali sa himagsikan, ano ang ikinabubuhay ni Macario Sakay?",
        choices: ["Guro at manunulat", "Mananahi at barbero", "Magsasaka at mangangalakal", "Kawani ng pamahalaan"],
        correct: 1 },
      { question: "Anong uri ng dulang panteatro ang madalas ginampanan ni Sakay noong kabataan niya?",
        choices: ["Sarswela", "Balagtasan", "Komedya o moro-moro", "Bodabil"],
        correct: 2 },
      { question: "Paano nakatutulong sa isang pinuno ang karanasan sa entablado?",
        choices: ["Nagbibigay ito ng yaman upang tustusan ang kilusan", "Nagbibigay ito ng koneksyon sa mga awtoridad", "Nagpapalakas ito ng katawan para sa labanan", "Nagsasanay ito sa pagsasalita sa harap ng maraming tao"],
        correct: 3 },
      { question: "Anong lihim na samahan ang sinalihan ni Macario Sakay noong 1894?",
        choices: ["La Liga Filipina", "Katipunan", "Propaganda Movement", "Guardia Civil"],
        correct: 1 },
      { question: "Ano ang pangunahing layunin ng Katipunan nang ito ay itatag?",
        choices: ["Makamit ang kalayaan mula sa Espanya sa pamamagitan ng himagsikan", "Humiling ng reporma sa pamahalaang Kastila", "Magtatag ng mga paaralan para sa mga Pilipino", "Makipagkalakalan sa ibang bansa"],
        correct: 0 },
      { question: "Bakit kinailangang manatiling lihim ang Katipunan?",
        choices: ["Dahil kakaunti lamang ang miyembro nito", "Dahil wala pa itong sapat na salapi", "Dahil ito ay isang samahang panrelihiyon", "Dahil ipinagbabawal ito at parurusahan ng mga awtoridad"],
        correct: 3 },
      { question: "Bakit mahalaga ang mga tagapaghatid ng mensahe sa isang lihim na kilusan?",
        choices: ["Sila ang nag-iimbak ng mga sandata", "Sila ang nagdadala ng balita nang hindi nabubunyag ang kilusan", "Sila ang laging nangunguna sa labanan", "Sila ang humahalili sa pinuno kapag wala ito"],
        correct: 1 },
      { question: "Ano ang ipinapakita kapag iniwan ng isang tao ang kanyang matatag na hanapbuhay upang sumali sa isang mapanganib na kilusan?",
        choices: ["Kawalan ng kakayahan sa kanyang trabaho", "Pagnanais na yumaman sa madaling paraan", "Handa siyang isakripisyo ang sariling kapakanan para sa layunin", "Pagsunod lamang sa utos ng kanyang pamilya"],
        correct: 2 },
      { question: "Kung ang isang kilusan ay binubuo ng mga karaniwang manggagawa, ano ang ipinapakita nito tungkol sa kilusang iyon?",
        choices: ["Ito ay kilusan ng mga mayayaman lamang", "Ito ay isang samahang pang-akademiko", "Ito ay itinatag at pinondohan ng mga dayuhan", "Ito ay kilusang bayan na may malawak na suporta mula sa mamamayan"],
        correct: 3 },
    ],
    post: [
      { question: "Aling lugar sa Maynila ang kinalakhan ni Macario Sakay?",
        choices: ["Malate", "Sampaloc", "Quiapo", "Tondo"],
        correct: 3 },
      { question: "Alin sa mga sumusunod na hanapbuhay ang ginawa ni Sakay bago siya naging Katipunero?",
        choices: ["Mangangalakal sa Binondo", "Tagapagturo sa isang paaralan", "Barbero at mananahi", "Marino sa daungan"],
        correct: 2 },
      { question: "Sa anong uri ng palabas madalas umarte si Sakay bago siya sumapi sa Katipunan?",
        choices: ["Moro-moro o komedya", "Sarswela", "Dulang panradyo", "Pantomima"],
        correct: 0 },
      { question: "Bakit naging kapaki-pakinabang kay Sakay ang kanyang karanasan sa komedya nang siya ay maging pinuno?",
        choices: ["Natuto siyang gumamit ng iba't ibang sandata", "Nakilala siya ng mga opisyal na Kastila", "Nahasa ang kanyang tinig at tapang na humarap sa madla", "Nakaipon siya ng malaking salapi mula rito"],
        correct: 2 },
      { question: "Saang samahan sumapi si Macario Sakay noong 1894?",
        choices: ["Cuerpo de Compromisarios", "La Solidaridad", "La Liga Filipina", "Katipunan"],
        correct: 3 },
      { question: "Ano ang hangarin ng Katipunan para sa Pilipinas?",
        choices: ["Pantay na karapatan bilang lalawigan ng Espanya", "Ganap na kalayaan sa pamamagitan ng armadong pakikibaka", "Pagbabago sa pamumuno ng simbahan", "Higit na malawak na kalakalan sa Asya"],
        correct: 1 },
      { question: "Bakit itinago ng mga Katipunero ang kanilang pagkakakilanlan at mga pagpupulong?",
        choices: ["Upang hindi sila mahuli at maparusahan ng mga awtoridad", "Upang hindi sila makilala ng ibang mga Pilipino", "Dahil ipinagbawal ito ng kanilang mga pamilya", "Upang makatipid sa gastos ng pagpupulong"],
        correct: 0 },
      { question: "Ano ang panganib na hinaharap ng isang Katipunerong naghahatid ng mensahe malapit sa kuta ng kaaway?",
        choices: ["Mawawala ang kanyang kabuhayan", "Mapapagalitan siya ng kanyang pinuno", "Mababawasan ang kanyang ranggo sa samahan", "Mahuhuli siya at malalantad ang buong kilusan"],
        correct: 3 },
      { question: "Ano ang ipinapahiwatig ng pasya ni Sakay na talikuran ang kanyang hanapbuhay upang sumapi sa Katipunan?",
        choices: ["Hindi siya mahusay sa kanyang trabaho", "Inuna niya ang kapakanan ng bayan kaysa sa sariling kaginhawahan", "Inaasahan niyang kikita nang malaki sa himagsikan", "Wala na siyang ibang mapagpipilian noon"],
        correct: 1 },
      { question: "Maraming karaniwang manggagawa, tulad ni Sakay, ang naging bahagi ng Katipunan. Ano ang sinasabi nito tungkol sa katangian ng Katipunan?",
        choices: ["Pinamunuan ito ng mga edukadong ilustrado lamang", "Isa itong kilusang nag-ugat sa karaniwang mamamayan", "Umasa ito sa tulong ng ibang bansa", "Bukas lamang ito sa mga taga-Maynila"],
        correct: 1 },
    ],
  },

  // Acts II to IV (9 Oct 2026, at the proponent's word): the same shape
  // as Act I's, ten matched pairs each, drawn from what the act shows and
  // from its three Talaan papers, so a student who played and read them
  // has met every answer. Each trivia card is a fact the act does not
  // test, so it hands no pre-test answer.
  2: {
    passing: 0.75,
    trivia: "Itinatag ang Katipunan noong gabi ng Hulyo 7, 1892, sa Tondo, nang mabalitang ipatatapon si Jose Rizal sa Dapitan. Pagsapit ng 1896, libu-libo na ang kasapi nito, at hindi na nito maitatago ang sarili nang matagal.",
    pre: [
      { question: "Sino ang patnugot ng Kalayaan, ang pahayagan ng Katipunan?",
        choices: ["Andres Bonifacio", "Emilio Jacinto", "Jose Rizal", "Marcelo H. del Pilar"],
        correct: 1 },
      { question: "Bakit isinulat sa Kalayaan na sa Yokohama, Hapon ito inilimbag?",
        choices: ["Upang linlangin ang mga Kastila kung saan ito ginawa", "Dahil mas mura ang paglilimbag sa Hapon", "Dahil mga Hapon ang sumulat nito", "Upang mabasa rin ito ng mga Hapon"],
        correct: 0 },
      { question: "Paano natuklasan ng mga Kastila ang lihim ng Katipunan noong Agosto 1896?",
        choices: ["Nahuli si Bonifacio sa isang pulong", "Nabasa nila ang Kalayaan sa isang tindahan", "Ipinagtapat ito ng kasaping si Teodoro Patiño sa kura ng Tondo", "Isinuplong ito ng isang sundalong Pilipino sa gobernador"],
        correct: 2 },
      { question: "Ano ang ibig sabihin ng pagpunit ng mga Katipunero sa kanilang sedula noong Agosto 1896?",
        choices: ["Ayaw na nilang magbayad ng buwis sa simbahan", "Wala na silang pakinabang sa sedula", "Iyon ang utos ng pamahalaang Kastila", "Itinatakwil nila ang pamahalaang Kastila at sinisimulan ang paghihimagsik"],
        correct: 3 },
      { question: "Ano ang nilusob ng mga Katipunero sa San Juan del Monte noong Agosto 30, 1896?",
        choices: ["Ang palasyo ng gobernador-heneral", "Ang polvorin o imbakan ng pulbura ng mga Kastila", "Ang simbahan ng Tondo", "Ang daungan ng Maynila"],
        correct: 1 },
      { question: "Ano ang kinahinatnan ng paglusob sa San Juan del Monte?",
        choices: ["Natalo ang mga Katipunero at mahigit 150 ang nasawi", "Nakuha ng Katipunan ang buong Maynila", "Sumuko ang mga Kastila nang walang laban", "Walang nasawi sa magkabilang panig"],
        correct: 0 },
      { question: "Ano ang nangyari sa Biak-na-Bato noong Disyembre 1897?",
        choices: ["Itinatag doon ang Katipunan", "Nahuli roon si Andres Bonifacio", "Lumagda ng kasunduan sa Espanya ang mga pinuno ng himagsikan at naglayag sila patungong Hong Kong", "Idineklara roon ang kalayaan ng Pilipinas"],
        correct: 2 },
      { question: "Kailan at saan idineklara ang kalayaan ng Pilipinas?",
        choices: ["Agosto 30, 1896, sa San Juan del Monte", "Disyembre 1897, sa Biak-na-Bato", "Hulyo 7, 1892, sa Tondo", "Hunyo 12, 1898, sa Kawit"],
        correct: 3 },
      { question: "Ayon sa Kasunduan sa Paris noong Disyembre 1898, ano ang nangyari sa Pilipinas?",
        choices: ["Kinilala ng Espanya ang kalayaan ng Pilipinas", "Ipinagbili ito ng Espanya sa Amerika sa halagang dalawampung milyong dolyar", "Hinati ito ng Espanya at ng Hapon", "Ibinalik ito sa pamumuno ng mga Katipunero"],
        correct: 1 },
      { question: "Nang kakaunti na lamang ang natitira sa Katipunan, nanatili pa rin si Sakay. Ano ang ipinapakita nito?",
        choices: ["Wala na siyang ibang mapupuntahan", "Umaasa siyang gagantimpalaan siya", "Natatakot siyang parusahan kung aalis", "Tapat siya sa kanyang sinumpaan kahit humihina ang kilusan"],
        correct: 3 },
    ],
    post: [
      { question: "Ang Kalayaan, ang pahayagan ng Katipunan, ay pinamatnugutan ni:",
        choices: ["Graciano Lopez Jaena", "Apolinario Mabini", "Emilio Aguinaldo", "Emilio Jacinto"],
        correct: 3 },
      { question: "Ano ang layunin ng pagsulat sa Kalayaan na inilimbag ito sa Yokohama, Hapon?",
        choices: ["Ipakita na may tulong ang Hapon sa Katipunan", "Ipagmalaki ang husay ng mga manlilimbag na Hapon", "Iligaw ang mga Kastila upang hindi matunton ang tunay na imprenta", "Makahikayat ng mga kasaping Hapon"],
        correct: 2 },
      { question: "Kanino ipinagtapat ni Teodoro Patiño ang lihim ng Katipunan noong Agosto 19, 1896?",
        choices: ["Kay Padre Mariano Gil, ang kura ng Tondo", "Sa gobernador-heneral ng Pilipinas", "Kay Andres Bonifacio", "Sa isang opisyal ng Guardia Civil"],
        correct: 0 },
      { question: "Bakit pinunit ng mga Katipunero ang kanilang sedula noong huling linggo ng Agosto 1896?",
        choices: ["Bilang tanda ng paghihimagsik laban sa Espanya", "Dahil luma na ang kanilang mga sedula", "Upang hindi sila makilala ng mga kapwa Pilipino", "Dahil iniutos ito ng kura ng kanilang bayan"],
        correct: 0 },
      { question: "Ano ang pakay ng mga Katipunero sa paglusob sa San Juan del Monte noong 1896?",
        choices: ["Iligtas si Jose Rizal sa bilangguan", "Sakupin ang palengke ng bayan", "Kunin ang polvorin, ang imbakan ng pulbura ng mga Kastila", "Sunugin ang mga talaan ng buwis"],
        correct: 2 },
      { question: "Ilan ang nasawing Katipunero sa labanan sa San Juan del Monte?",
        choices: ["Wala ni isa", "Mga sampu", "Mga limampu", "Mahigit 150"],
        correct: 3 },
      { question: "Ano ang naging bunga ng kasunduan sa Biak-na-Bato noong Disyembre 1897?",
        choices: ["Naglayag ang mga pinuno ng himagsikan patungong Hong Kong", "Nagkaroon ng Asamblea ang mga Pilipino", "Umalis ang lahat ng Kastila sa Pilipinas", "Napalaya si Jose Rizal"],
        correct: 0 },
      { question: "Ano ang nangyari sa Kawit noong Hunyo 12, 1898?",
        choices: ["Itinatag ang Katipunan", "Nilagdaan ang Kasunduan sa Paris", "Idineklara ang kalayaan ng Pilipinas", "Nagsimula ang labanan sa San Juan del Monte"],
        correct: 2 },
      { question: "Sa halagang dalawampung milyong dolyar, ano ang ginawa ng Espanya sa Kasunduan sa Paris?",
        choices: ["Binili ang Cuba mula sa Amerika", "Nagtayo ng mga paaralan sa Maynila", "Binayaran ang mga Pilipino para sa digmaan", "Ipinagbili ang Pilipinas sa Amerika"],
        correct: 3 },
      { question: "Sinabi ni Sakay kay Jacinto: \"Sa Katipunan ako nanumpa.\" Ano ang ipinapakita ng kanyang pasyang manatili kahit humihina ang kilusan?",
        choices: ["Katapatan sa layuning kanyang sinumpaan", "Pagnanais na maging pinuno ng Katipunan", "Kawalan ng ibang hanapbuhay", "Pagsunod lamang sa utos ng kanyang ina"],
        correct: 0 },
    ],
  },

  3: {
    passing: 0.75,
    trivia: "Noong Abril 16, 1899, namatay sa malaria si Emilio Jacinto sa Majayjay, Laguna. Dalawampu't tatlong taong gulang lamang siya. Tinawag siyang \"Utak ng Katipunan\".",
    pre: [
      { question: "Saan nagsimula ang Digmaang Pilipino-Amerikano noong gabi ng Pebrero 4, 1899?",
        choices: ["Sa Santa Mesa, Maynila", "Sa Kawit, Cavite", "Sa Malolos, Bulacan", "Sa Palanan, Isabela"],
        correct: 0 },
      { question: "Saan nahuli ng mga Amerikano si Emilio Aguinaldo noong Marso 1901?",
        choices: ["Sa Tondo, Maynila", "Sa Palanan, Isabela", "Sa Biak-na-Bato, Bulacan", "Sa Morong, Rizal"],
        correct: 1 },
      { question: "Anong partido ang itinatag noong 1901 kung saan naging Kalihim-Heneral si Macario Sakay?",
        choices: ["Partido Federal", "La Liga Filipina", "Partido Nacionalista", "Partido Liberal"],
        correct: 2 },
      { question: "Paano hinangad ng Partido Nacionalista na makamit ang kalayaan?",
        choices: ["Sa pamamagitan ng armadong paglusob sa Maynila", "Sa paghingi ng tulong sa Hapon", "Sa pagsuko sa mga Amerikano", "Sa mapayapa at legal na paraan, tulad ng petisyon"],
        correct: 3 },
      { question: "Ano ang ginawang krimen ng Batas sa Sedisyon (Batas Bilang 292) noong 1901?",
        choices: ["Ang pagsusulong ng kalayaan, sa salita man o sa sulat, kahit sa mapayapang paraan", "Ang pagbebenta ng bigas sa ibang bayan", "Ang pagpasok sa paaralang Amerikano", "Ang pagsasalita ng Ingles"],
        correct: 0 },
      { question: "Bakit nakalaya si Sakay mula sa Bilibid noong 1902?",
        choices: ["Tumakas siya sa gabi", "Dahil sa amnestiyang ibinigay nang ideklara ng mga Amerikano na tapos na ang digmaan", "Binayaran ng kanyang mga kasama ang piyansa", "Napatunayang wala siyang kasalanan sa hukuman"],
        correct: 1 },
      { question: "Anong pamahalaan ang itinatag ni Sakay sa kabundukan ng Morong noong 1902?",
        choices: ["Republika ng Biak-na-Bato", "Republika ng Malolos", "Republika ng Katagalugan", "Pamahalaang Diktatoryal"],
        correct: 2 },
      { question: "Saan ibinatay ang saligang batas ng Republika ng Katagalugan?",
        choices: ["Sa saligang batas ng Amerika", "Sa mga batas ng Espanya", "Sa mga utos ng Komisyon ng Pilipinas", "Sa mga aral ni Andres Bonifacio at ng Katipunan"],
        correct: 3 },
      { question: "Ayon sa Batas sa Bandolerismo ng Nobyembre 1902, ano ang itinawag ng mga Amerikano sa mga patuloy na lumalaban?",
        choices: ["Mga bayani", "Mga bandido", "Mga sundalo", "Mga rebolusyonaryo"],
        correct: 1 },
      { question: "Nanumpa si Sakay at ang kanyang mga tauhan na hindi gugupitin ang kanilang buhok hangga't hindi malaya ang bayan. Ano ang ipinapakita nito?",
        choices: ["Matibay nilang paninindigan na ituloy ang laban hanggang makamit ang kalayaan", "Wala silang barbero sa bundok", "Isa itong kaugalian ng mga Amerikano", "Nais nilang magtago sa mga kapwa Pilipino"],
        correct: 0 },
    ],
    post: [
      { question: "Ang pamamaril ng isang bantay na Amerikano sa Santa Mesa noong Pebrero 4, 1899 ay naging simula ng:",
        choices: ["Himagsikang 1896", "Kasunduan sa Biak-na-Bato", "Digmaang Pilipino-Amerikano", "Pagtatatag ng Katipunan"],
        correct: 2 },
      { question: "Anong pangyayari noong Marso 1901 sa Palanan, Isabela ang nagpahina sa paglaban sa mga Amerikano?",
        choices: ["Ang pagkamatay ni Emilio Jacinto", "Ang pagdating ng Konstabularya", "Ang pagkakatatag ng Asamblea", "Ang pagkadakip kay Emilio Aguinaldo"],
        correct: 3 },
      { question: "Anong tungkulin ang hinawakan ni Sakay sa Partido Nacionalista nang itatag ito noong 1901?",
        choices: ["Kalihim-Heneral", "Tagapagsalita sa Amerika", "Ingat-yaman", "Pangulo"],
        correct: 0 },
      { question: "Ano ang paraan ng Partido Nacionalista sa paghingi ng kalayaan bago ito ipagbawal?",
        choices: ["Petisyon sa mga awtoridad na Amerikano, sa legal at mapayapang paraan", "Pagsalakay sa mga himpilan ng Amerikano", "Pagtatago sa kabundukan", "Paglilimbag ng pahayagan sa Hapon"],
        correct: 0 },
      { question: "Bakit itinuring na mapanganib ng mga Pilipino ang Batas sa Sedisyon ng 1901?",
        choices: ["Dahil itinaas nito ang buwis sa bigas", "Dahil ipinagbawal nito ang pagsasalita ng Tagalog", "Dahil isinara nito ang lahat ng paaralan", "Dahil kahit ang mapayapang pagsusulong ng kalayaan ay ginawa nitong krimen"],
        correct: 3 },
      { question: "Ano ang nagpalaya kay Sakay at sa ibang bilanggong Pilipino sa Bilibid noong 1902?",
        choices: ["Isang kasunduan sa Espanya", "Ang utos ni Emilio Aguinaldo", "Isang paglusob ng kanyang mga kasama", "Ang amnestiyang kasunod ng pagdeklara ng mga Amerikano na tapos na ang digmaan"],
        correct: 3 },
      { question: "Sino ang Pangulo ng Republika ng Katagalugan na itinatag sa kabundukan ng Morong?",
        choices: ["Macario Sakay", "Emilio Aguinaldo", "Francisco Carreón", "Julian Montalan"],
        correct: 0 },
      { question: "Ano ang ginawang saligang batas ng Republika ng Katagalugan?",
        choices: ["Ang Batas Bilang 292", "Ang mga aral ng Katipunan ni Andres Bonifacio", "Ang Kasunduan sa Paris", "Ang Saligang Batas ng Malolos"],
        correct: 1 },
      { question: "Ano ang epekto ng Batas sa Bandolerismo ng 1902 sa mga patuloy na lumalaban sa mga Amerikano?",
        choices: ["Tinawag silang mga bandido at kamatayan ang parusa", "Pinayagan silang bumuo ng partido", "Kinilala sila bilang mga sundalo ng isang bansa", "Binigyan sila ng lupa"],
        correct: 0 },
      { question: "Ano ang sinasagisag ng mahabang buhok ni Sakay at ng kanyang mga tauhan?",
        choices: ["Ang pagsunod sa uso ng panahon", "Ang kanilang panata na lumaban hangga't hindi malaya ang bayan", "Ang kanilang pagiging mga artista ng komedya", "Ang kanilang pagsuko sa mga Amerikano"],
        correct: 1 },
    ],
  },

  4: {
    passing: 0.75,
    trivia: "Noong Marso 18, 1903, inilabas ni Macario Sakay ang Unang Kautusan bilang Pangulo ng Republika ng Katagalugan. Sa kabundukan, may sarili itong hukbo, sariling mga kautusan at sariling watawat, habang ang Maynila ay nasa kamay ng mga Amerikano.",
    pre: [
      { question: "Ano ang ipinahayag ng manipesto ni Sakay noong Abril 5, 1904?",
        choices: ["Na susuko na siya sa mga Amerikano", "Na may buong karapatan ang mga Pilipino na ipaglaban ang kanilang kalayaan", "Na lilipat siya sa Hong Kong", "Na sasali siya sa Partido Federal"],
        correct: 1 },
      { question: "Bakit inipon ng mga Amerikano ang mga taga-baryo ng Cavite at Batangas sa mga kampong may bantay noong 1905?",
        choices: ["Upang putulin ang pagkain at tulong ng mga mamamayan sa mga lumalaban sa bundok", "Upang turuan sila ng Ingles", "Upang ilayo sila sa bagyo", "Upang bigyan sila ng bagong lupa"],
        correct: 0 },
      { question: "Ano ang naging epekto ng rekonsentrasyon sa mga taga-baryo?",
        choices: ["Yumaman sila sa kalakalan", "Nakapag-aral sila nang libre", "Nagutom sila at nawalan ng kabuhayan", "Naging kasapi sila ng Konstabularya"],
        correct: 2 },
      { question: "Sino ang lider-manggagawa na nakipag-usap kay Sakay noong 1906 upang bumaba ito mula sa bundok?",
        choices: ["Emilio Aguinaldo", "Pascual Poblete", "Julian Montalan", "Dominador Gómez"],
        correct: 3 },
      { question: "Bakit pumayag si Sakay na bumaba mula sa bundok noong 1906?",
        choices: ["Dahil naubusan na siya ng tauhan", "Dahil ipinangakong mabubuksan ang Asamblea ng Pilipinas kapag natapos ang labanan", "Dahil inalok siya ng malaking halaga", "Dahil may sakit siya"],
        correct: 1 },
      { question: "Alin ang isa sa mga kondisyong hiningi ni Sakay bago siya bumaba mula sa bundok?",
        choices: ["Amnestiya para sa kanyang mga tauhan", "Isang upuan sa Asamblea para sa kanya", "Lupa sa Cavite para sa kanyang pamilya", "Ang pag-alis ng lahat ng Amerikano sa loob ng isang buwan"],
        correct: 0 },
      { question: "Ano ang nangyari kay Sakay sa salu-salo sa Cavite noong Hulyo 17, 1906?",
        choices: ["Ginawaran siya ng medalya", "Nahalal siya sa Asamblea", "Dinakip siya at ang kanyang mga opisyal", "Lumagda siya ng kasunduang pangkapayapaan"],
        correct: 2 },
      { question: "Sa anong kaso hinatulan ng kamatayan si Sakay?",
        choices: ["Pagnanakaw ng salapi ng pamahalaan", "Pagtataksil sa Espanya", "Pagsunog sa isang simbahan", "Bandolerismo, o pagiging bandido"],
        correct: 3 },
      { question: "Ano ang nangyari noong Oktubre 16, 1907, tatlumpu't tatlong araw matapos bitayin si Sakay?",
        choices: ["Binuksan ang Asamblea ng Pilipinas", "Idineklara ang kalayaan ng Pilipinas", "Itinatag ang Katipunan", "Nagsimula ang Digmaang Pilipino-Amerikano"],
        correct: 0 },
      { question: "Sa kanyang huling pahayag, ano ang nais patunayan ni Sakay?",
        choices: ["Na pinagsisisihan niya ang paglaban", "Na sila ay kasapi ng hukbong rebolusyonaryo na nagtanggol sa bayan, hindi mga bandido", "Na dapat nang sumuko ang lahat ng Pilipino", "Na wala siyang kinalaman sa Republika ng Katagalugan"],
        correct: 1 },
    ],
    post: [
      { question: "Ayon sa manipesto ni Sakay noong 1904, ano ang karapatan ng mga Pilipino?",
        choices: ["Ang bumoto sa halalan ng Amerika", "Ang maglakbay sa ibang bansa", "Ang ipaglaban ang kanilang kalayaan", "Ang magtayo ng sariling paaralan"],
        correct: 2 },
      { question: "Ano ang tunay na layunin ng rekonsentrasyon sa Cavite at Batangas noong 1905?",
        choices: ["Protektahan ang mga taga-baryo laban sa mga bandido", "Magtayo ng mga bagong bayan", "Bilangin ang populasyon", "Pigilan ang mga mamamayan na magbigay ng pagkain at tulong sa mga lumalaban"],
        correct: 3 },
      { question: "Ano ang dinanas ng mga taga-baryong inipon sa mga kampo noong 1905?",
        choices: ["Gutom at paghihirap", "Kasaganaan ng pagkain", "Libreng tirahan sa Maynila", "Mas mataas na sahod"],
        correct: 0 },
      { question: "Sino si Dominador Gómez sa kuwento ni Sakay?",
        choices: ["Ang hukom na naghatol sa kanya", "Ang lider-manggagawa na nakipag-usap sa kanya upang bumaba mula sa bundok", "Ang Pangalawang Pangulo ng Republika ng Katagalugan", "Ang koronel na Amerikano na nag-anyaya sa kanya"],
        correct: 1 },
      { question: "Ano ang ipinangako kay Sakay kapalit ng kanyang pagbaba mula sa bundok?",
        choices: ["Na siya ang magiging gobernador ng Cavite", "Na ibabalik ang Pilipinas sa Espanya", "Na mabubuksan ang Asamblea ng Pilipinas kapag natapos ang labanan", "Na bibigyan siya ng lupain sa Maynila"],
        correct: 2 },
      { question: "Alin sa mga sumusunod ang kabilang sa mga hiningi ni Sakay bago siya sumuko?",
        choices: ["Na palayain ang lahat ng bilanggo sa Hong Kong", "Na siya ang mamuno sa Konstabularya", "Na isara ang Bilibid", "Na payagan siya at ang kanyang mga opisyal na lumabas ng bansa"],
        correct: 3 },
      { question: "Ano ang naging kapalaran ni Sakay sa salu-salong idinaos ni Koronel Van Schaick sa Cavite?",
        choices: ["Siya ay dinakip at dinisarmahan", "Siya ay pinarangalan bilang bayani", "Siya ay hinirang na opisyal ng Amerika", "Siya ay pinauwi sa Tondo"],
        correct: 0 },
      { question: "Sa ilalim ng anong paratang hinatulan ng kamatayan si Sakay at ang kanyang mga kasama?",
        choices: ["Sedisyon", "Bandolerismo", "Pagtakas sa bilangguan", "Pagsira ng ari-arian"],
        correct: 1 },
      { question: "Kailan binitay si Sakay, at ano ang nangyari tatlumpu't tatlong araw pagkaraan?",
        choices: ["Hulyo 1906; nagsimula ang digmaan", "Disyembre 1898; nilagdaan ang Kasunduan sa Paris", "Setyembre 13, 1907; binuksan ang Asamblea ng Pilipinas", "Marso 1903; itinatag ang Republika ng Katagalugan"],
        correct: 2 },
      { question: "\"Hindi kami mga bandido at magnanakaw.\" Ano ang ipinaglaban ni Sakay sa kanyang huling pahayag?",
        choices: ["Ang kanyang kayamanan", "Ang kanyang pagkakaibigan sa mga Amerikano", "Ang kanyang karapatang tumira sa Maynila", "Ang dangal ng kanilang laban bilang mga rebolusyonaryong nagtanggol sa bayan"],
        correct: 3 },
    ],
  },
};
